### ISSUE TITLE
Exception when connecting

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tjofle/clementine-webremote#1]
```
After trying to open in the browser:

Exception happened during processing of request from ('192.168.1.7', 48530)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 284, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 310, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 639, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 343, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 331, in handle_one_request
    method()
  File "http.py", line 46, in do_GET
    self.wfile.write(web.PrintHeader())
  File "/home/magnes/skrypty/clementremote/web.py", line 34, in PrintHeader
    <title>" + self.info['artist'] + " - " + self.info['title'] + "</title>\n\
KeyError: 'artist'

```

Original issue reported on code.google.com by `magne...@gmail.com` on 10 Jul 2011 at 8:12

**Comment by GoogleCodeExporter** [comment]
```
Try with the new version, probably with the utf8 encoding this problem has been 
fixed.
Thanks
```

Original comment by `hector.f...@gmail.com` on 2 Oct 2011 at 1:32
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
The new version works.
```

Original comment by `magne...@gmail.com` on 2 Oct 2011 at 1:51

**Comment by GoogleCodeExporter** [comment]
```
Perfect!
```

Original comment by `hector.f...@gmail.com` on 2 Oct 2011 at 2:01
- Changed state: **Fixed**
