### ISSUE TITLE
Broken Pipe Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tjofle/clementine-webremote#5]
```
While I was testing the python script (By the way, thank you a lot!) with 3 
devices and my computer... I saw the console flooded with the next message:

----------------------------------------
192.168.1.105 - - [26/Oct/2011 17:13:43] "GET /refresh HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.105', 1566)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 284, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 310, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 641, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 694, in finish
    self.wfile.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------

And also, eventually something makes the script to get very slow and 
unrresponsive. Maybe I wass adding to much stress to it.
```

Original issue reported on code.google.com by `kadaimx` on 26 Oct 2011 at 10:17

**Comment by GoogleCodeExporter** [comment]
```
Aloha,

Came across your script today. I installed and ran the script on a system with 
Ubuntu 12.04. I was able to run the script, and on my laptop I can pull up the 
page and it works. 

I installed clementine-remote-android on my phone. The application sits on the 
main screen saying 'connecting to clementine' when I exit out of the 
application, your script throws the following error:

BEGIN QUOTE
Exception happened during processing of request from ('192.168.0.191', 50452)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 704, in finish
    self.wfile.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
 END QUOTE

I do not know if the issue is with the android application or your script.
```

Original comment by `sigmarho...@gmail.com` on 18 Feb 2013 at 2:57
