### ISSUE TITLE
Can't find 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tjofle/clementine-webremote#7]
```
What steps will reproduce the problem?
1. Start Clementine
2. Start the script
3. Connect

What is the expected output?

What do you see instead?
$ /home/testman/clementine-webremote-0.2/http.py --port 3000
Incorrect port, launching at 3000.
Using port: 3000
192.168.0.99 - - [01/Jan/2012 08:52:09] "GET / HTTP/1.1" 200 -
Clementine is stopped
----------------------------------------
Exception happened during processing of request from ('192.168.0.99', 52095)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 284, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 310, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 639, in __init__
    self.handle()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 343, in handle
    self.handle_one_request()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 331, in handle_one_request
    method()
  File "/home/mcman/clementine-webremote-0.2/http.py", line 43, in do_GET
    f = open('style.css')
IOError: [Errno 2] No such file or directory: 'style.css'
----------------------------------------
192.168.0.99 - - [01/Jan/2012 08:52:09] "GET /favicon.ico HTTP/1.1" 200 -
Clementine is stopped
192.168.0.99 - - [01/Jan/2012 08:52:09] "GET /favicon.ico HTTP/1.1" 200 -
Clementine is stopped


What version of the product are you using? On what operating system?

openSUSE 11.4 and 12.1

Please provide any additional information below.


```

Original issue reported on code.google.com by `waxb...@gmail.com` on 1 Jan 2012 at 7:07

**Comment by GoogleCodeExporter** [comment]
```
From your post I assume your problem is that you cant find external files such 
as "style.css".

This is because you launched the script from your home-folder, and the script 
uses relative paths, so it looks for "style.css" in /home/testman/.

I'll look into fixing this in the source-code, but in the meantime I suggest 
you "cd" to your clementineWebRemote-folder and then launch the script.
```

Original comment by `tjo...@gmail.com` on 18 Oct 2012 at 7:22
- Changed state: **Accepted**
